version: '3.9'
networks:
    ota:
      driver: bridge

services: 
  ota-mongo:
    container_name: ota-mongo
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
        - mongodb-data:/var/lib/mongodb/data
    networks:
        - ota
        
  ota-backend:
    container_name: api
    build:
      context: './backend'
      dockerfile: 'Dockerfile'
    image: 'corey773/ota:latest'
    ports:
      - '8000:8000'
    environment:
      - MONGO_URI=mongodb://ota-mongo:27017
    depends_on: 
        - ota-mongo
    networks:
        - ota
        
volumes:
  mongodb-data:
      